// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';

export function CloseFile(arg1:string):Promise<void>;

export function GetPropValues(arg1:string,arg2:string):Promise<Array<string>>;

export function LoadFile(arg1:string):Promise<store.FileMetadata>;

export function OpenFileDialog():Promise<Array<string>>;
