// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SelectFile():Promise<string>;

export function StartTailing():Promise<void>;

export function StopTailing():Promise<void>;
