// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function StartTailing() {
  return window['go']['main']['App']['StartTailing']();
}

export function StopTailing() {
  return window['go']['main']['App']['StopTailing']();
}
