// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function SelectFile():Promise<models.WatchInfo>;

export function StopTailing(arg1:string):Promise<void>;
