// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseFile(arg1) {
  return window['go']['main']['App']['CloseFile'](arg1);
}

export function GetPropValues(arg1, arg2) {
  return window['go']['main']['App']['GetPropValues'](arg1, arg2);
}

export function LoadFile(arg1) {
  return window['go']['main']['App']['LoadFile'](arg1);
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}
